import type { ArticleFetchSiteSpec } from '@collectors/web/article-fetch-sites/site-spec';

export const DEDAO_NOTE_DETAIL_SITE_SPEC: ArticleFetchSiteSpec = {
  id: 'dedao_note_detail',
  urlPattern: /^https?:\/\/(?:www\.)?dedao\.cn\/knowledge\/note\/detail\b/i,
  rootSelector: '#leftContent .left-content',
  titleFallbackOrder: ['document', 'meta'],
  authorSelector: '.audio-info .name',
  publishedAtSelector: '.audio-info .date',
  textPrefer: 'textContent',
  useSanitizedRootHtml: true,
  removeSelectors: [
    '.autor-right',
    '#knowledge-option',
    '.attention',
    '.iget-prompt',
    '#recommendUser',
    '#recommendList',
    '.feed-btn-recommendation',
    '.pointer',
    '.note-expo',
    '.operation-area',
    '.loading-more',
    '.write-comment',
    '.iget-drop-down-card',
    '.forward-list',
    '.like-list',
    '.list-header .tab:not(.active-tab)',
    '.active-tab-pointer',
    '.audio-info .cover',
    '.audio-info .img-v',
  ],
};
